# Generated by Django 2.2.5 on 2019-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarticle',
            name='short_description',
            field=models.CharField(default='', max_length=200, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
