# Generated by Django 3.0.6 on 2021-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200528_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarticle',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
