# Generated by Django 2.2.5 on 2019-12-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191210_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images', verbose_name='Рисунок'),
        ),
    ]
