# Generated by Django 2.2.5 on 2019-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_images', verbose_name='Рисунок'),
        ),
    ]
