# Generated by Django 3.0.6 on 2020-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200528_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
