# Generated by Django 3.0.6 on 2020-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200528_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
