# Generated by Django 3.0.6 on 2020-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200528_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
