# Generated by Django 3.0.6 on 2020-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='filestorage/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
