# Generated by Django 3.0.6 on 2020-06-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_auto_20200618_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
