# Generated by Django 3.0.6 on 2020-05-27 07:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное наименование')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('image', models.ImageField(default='product_default.png', upload_to='products')),
                ('short_description', models.TextField(default='', verbose_name='Краткое описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('used_in_poultry', models.BooleanField(default=False, verbose_name='Используется в птицекомплексах')),
                ('used_in_pigsty', models.BooleanField(default=False, verbose_name='Используется в свинокомплексах')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(default='topic_icon_default.png', upload_to='topic_icons')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Оглавление')),
                ('specification', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Раздел описания продукта',
                'verbose_name_plural': 'Разделы описания продукта',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductTopic', verbose_name='Категория продукта'),
        ),
    ]
