# Generated by Django 3.0.6 on 2020-05-27 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttopic',
            name='icon',
            field=models.FileField(default='topic_icon_default.png', upload_to='topic_icons', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка (.svg)'),
        ),
    ]
