# Generated by Django 3.0.6 on 2020-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200527_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttopic',
            name='icon',
        ),
        migrations.AddField(
            model_name='producttopic',
            name='icon_class',
            field=models.CharField(default='icon-fan', max_length=100, verbose_name='Символ иконки (CSS-класс)'),
        ),
    ]
