# Generated by Django 2.2.5 on 2019-11-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191129_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttopic',
            old_name='display_order',
            new_name='order',
        ),
    ]
