# Generated by Django 2.2.5 on 2019-12-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191129_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_default.jpg', upload_to='product_pictures'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_in_pigsty',
            field=models.BooleanField(default=False, verbose_name='Используется в свинокомплексах'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_in_poultry',
            field=models.BooleanField(default=False, verbose_name='Используется в птицекомплексах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Наименование'),
        ),
    ]
