# Generated by Django 2.2.5 on 2019-12-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191205_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedline', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
                ('topics', models.ManyToManyField(to='products.ProductTopic', verbose_name='Категории продуктов')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
