# Generated by Django 2.2.5 on 2019-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_topicsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicsgroup',
            name='hedline',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topicsgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
