# Generated by Django 2.2.5 on 2019-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191210_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttopic',
            name='icon',
            field=models.ImageField(default='topic_icon_default.png', upload_to='topic_icons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_default.png', upload_to='product_pictures'),
        ),
    ]
