# Generated by Django 2.2.5 on 2019-12-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191210_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product')),
                ('specifications', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('func_scheme', models.ImageField(blank=True, upload_to='product_schemes', verbose_name='Функциональная схема')),
                ('сontrols_description', models.TextField(blank=True, verbose_name='Элементы управления')),
                ('dimensions', models.TextField(blank=True, verbose_name='Габаритные размеры')),
                ('connection_scheme', models.ImageField(blank=True, upload_to='product_schemes', verbose_name='Функциональная схема')),
                ('documentation', models.TextField(blank=True, verbose_name='Документация')),
                ('package_bundle', models.TextField(blank=True, verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Спецификация продукта',
                'verbose_name_plural': 'Спецификации продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=1, max_length=50, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Полное наименование'),
        ),
    ]
