# Generated by Django 2.2.5 on 2019-12-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191211_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicsgroup',
            old_name='hedline',
            new_name='headline',
        ),
    ]
