# Generated by Django 2.2.5 on 2019-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191211_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='connection_scheme',
            field=models.ImageField(blank=True, upload_to='product_schemes', verbose_name='Cхемы подключения'),
        ),
    ]
