# Generated by Django 3.0.6 on 2020-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200523_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecificationfield',
            options={'verbose_name': 'Раздел описания продукта', 'verbose_name_plural': 'Разделы описания продукта'},
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
    ]
