# Generated by Django 3.0.6 on 2020-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200523_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='productspecificationfield',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
