# Generated by Django 3.0.6 on 2020-05-24 09:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200524_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationfield',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
