# Generated by Django 3.0.6 on 2020-05-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200524_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicsGroup',
        ),
    ]
